Workbench
CivicScience/s3-flink-s3-poc pull request #8
Opened 2023-01-06 17:01 UTC by shanmukhipriya-ponnada

Pull request from workbench branch to main

Changes have been tested 

<img width="1496" alt="Screenshot 2023-01-06 at 11 01 09 AM" src="https://user-images.githubusercontent.com/115562771/211060745-a9e83625-6443-47e6-850c-7ecf805cb2bb.png">

2023-01-07 00:56 UTC, dkondratenkocs commented on pom.xml
> +      <version>7.8.0</version>
Can you put this version under <properties> tag

2023-01-07 01:13 UTC, dkondratenkocs requested changes

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/java/com/civicscience/datapipeline/FilePathFilterS3.java
> +            && Integer.parseInt(s[8]) >= limit.getMonthValue()
See my comment above

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/java/com/civicscience/entity/JotLog.java
>  @Setter
@Data annotation includes @Getter and @Setter. There is no need to have them separately

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/java/com/civicscience/metrics/JotLogFilterMetricsMapper.java
> +public class JotLogFilterMetricsMapper extends RichMapFunction<String, String> {
Please add javadoc

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/java/com/civicscience/metrics/JotLogTransformMetricMapper.java
> +public class JotLogTransformMetricMapper extends RichMapFunction<JotLog, JotLog> {
Please add javadoc

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/java/com/civicscience/utils/DataTransformation.java
> +  public JotLog mapToJotLogObject(String s) {
Please put javadoc with examples explaining why we are using indexes below

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/java/com/civicscience/utils/DataTransformation.java
> +    LOG.info("Transformed Jot log : {}", log);
Do we actually need to log every event? might be ratelimmiting/remove completely

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/java/com/civicscience/utils/DataTransformation.java
> +      LOG.info("d_element errored out : {}", d_element);
Do we need it?

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/resources/default-flink-params.yml
> +    filesink_bucket_name: "civicscience-dwf-prod-sink"
Please make sure if bucket exists. Let's create it

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/resources/default-flink-params.yml
> +    filesource_lookup_days_ago: 1
Do we need to set 18 month for dev?  if yes, please modify it to have 18 month - 548 days

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/resources/default-flink-params.yml
> +    filesource_lookup_days_ago: 1
please modify it to have 18 month - 548 days

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/java/com/civicscience/datapipeline/DataStreamJob.java
> +    FileSource<String> source = FileSource.forRecordStreamFormat(
Could you please add some comments here and below where it necessary what each block is doing for those who might be interested to have just an example.

2023-01-07 01:13 UTC, dkondratenkocs commented on src/main/java/com/civicscience/utils/DataTransformation.java
> +    Matcher m = Pattern.compile("([^\"]\\S*|\".+?\")\\s*").matcher(s);
Please move as field Pattern.compile("([^\"]\\S*|\".+?\")\\s*")

2023-01-09 14:57 UTC, shanmukhipriya-ponnada commented on src/main/java/com/civicscience/datapipeline/FilePathFilterS3.java
> +      if (s.length == 8 && Integer.parseInt(s[7]) >= limit.getYear()) {
Initially we tried regex, it was not working with our folder structure. I will add description to explain numbers

2023-01-09 14:58 UTC, shanmukhipriya-ponnada commented on pom.xml
> +      <version>7.8.0</version>
sure

2023-01-09 16:33 UTC, shanmukhipriya-ponnada commented on src/main/resources/default-flink-params.yml
> +    filesource_lookup_days_ago: 1
We can leave default value as 1 for dev, if someone wants to test or play around with the jar. This can be overwritten by passing arguments

2023-01-09 16:34 UTC, shanmukhipriya-ponnada commented on pom.xml
> +      <version>4.13.2</version>
sure

2023-01-09 16:34 UTC, shanmukhipriya-ponnada commented on src/main/java/com/civicscience/datapipeline/DataStreamJob.java
> +    FileSource<String> source = FileSource.forRecordStreamFormat(
sure

2023-01-09 21:49 UTC, shanmukhipriya-ponnada commented on pom.xml
> +      <version>7.8.0</version>
done

2023-01-09 21:50 UTC, shanmukhipriya-ponnada commented on src/main/java/com/civicscience/entity/JotLog.java
>  @Setter
Nice catch, removed them

2023-01-09 21:53 UTC, shanmukhipriya-ponnada commented on src/main/java/com/civicscience/metrics/JotLogFilterMetricsMapper.java
> +public class JotLogFilterMetricsMapper extends RichMapFunction<String, String> {
done

2023-01-09 21:54 UTC, shanmukhipriya-ponnada commented on src/main/java/com/civicscience/metrics/JotLogTransformMetricMapper.java
> +public class JotLogTransformMetricMapper extends RichMapFunction<JotLog, JotLog> {
done

2023-01-09 21:55 UTC, shanmukhipriya-ponnada commented on src/main/java/com/civicscience/utils/DataTransformation.java
> +      LOG.info("d_element errored out : {}", d_element);
Added this when debugging, will remove it

2023-01-09 21:58 UTC, shanmukhipriya-ponnada commented on src/main/resources/default-flink-params.yml
> +    filesource_lookup_days_ago: 1
Marc wants to discuss about this 18month period going back. Since we can configure this through params, maybe we can keep default to another smaller value?

2023-01-09 22:00 UTC, shanmukhipriya-ponnada commented on src/main/java/com/civicscience/utils/DataTransformation.java
> +      LOG.info("d_element errored out : {}", d_element);
this will only log for any exception, so not for every event

2023-01-09 22:10 UTC, shanmukhipriya-ponnada commented on src/main/resources/default-flink-params.yml
> +    filesink_bucket_name: "civicscience-dwf-prod-sink"
done

2023-01-09 22:40 UTC, shanmukhipriya-ponnada commented on src/main/java/com/civicscience/utils/DataTransformation.java
> +  public JotLog mapToJotLogObject(String s) {
done

2023-01-10 06:54 UTC, dkondratenkocs commented on src/main/java/com/civicscience/utils/DataTransformation.java
> +      LOG.info("d_element errored out : {}", d_element);
Yeah, it is only log if exception occurs. I think you confused with this comment (https://github.com/CivicScience/s3-flink-s3-poc/pull/8/files#r1063924255 ). It is better to make message more generic and log as error

2023-01-10 06:56 UTC, dkondratenkocs requested changes
Please check my latest comments and commit your changes to take a look

2023-01-10 15:02 UTC, shanmukhipriya-ponnada commented on src/main/java/com/civicscience/utils/DataTransformation.java
> +      LOG.info("d_element errored out : {}", d_element);
will do

2023-01-10 15:15 UTC, shanmukhipriya-ponnada commented on src/main/java/com/civicscience/utils/DataTransformation.java
> +    LOG.info("Transformed Jot log : {}", log);
removed it

2023-01-18 16:13 UTC, merged